# Generated by Django 4.0 on 2021-12-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=3)),
                ('arrival_airport', models.CharField(max_length=3)),
                ('departure_time', models.DateField()),
                ('arrival_time', models.DateField()),
                ('stops', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineraries.itinerary')),
            ],
        ),
    ]
