# Generated by Django 4.0 on 2021-12-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('itineraries', '0001_initial'),
        ('legs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legs',
            new_name='Leg',
        ),
    ]
