# Generated by Django 4.0 on 2022-01-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='agent',
        ),
        migrations.AddField(
            model_name='leg',
            name='airline',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='itineraries.airline'),
            preserve_default=False,
        ),
    ]
