# Generated by Django 4.0 on 2022-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_airline_remove_agent_api_id_remove_leg_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='duration_mins',
            field=models.IntegerField(default=0),
        ),
    ]
