# Generated by Django 4.0 on 2022-01-11 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_remove_itinerary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
